permalink: /blog/:categories/:title
defaults:
    -
        scope:
            path: ""
        values:
            layout: default
            links:
                Home: /
                Schedule: /schedule/
                Blog: /blog/

