permalink: /blog/:categories/:title.html
defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: default
            links:
                Home: /
                Schedule: /schedule/
                Blog: /blog/

