permalink: /blog/:categories/:title
defaults:
    -
        scope:
            path: ""
        values:
            layout: default
            links:
                - title: Home
                  ref: /
                  color: '#f44336'
                - title: Schedule
                  ref: /schedule/
                  color: '#03a9f4'
                - title: Projects
                  ref: /projects/
                  color: '#4caf50'
                - title: Blog
                  ref: /blog/
                  color: '#ff5722'

sass:
    style: compressed
    sass-dir: _sass

