permalink: /blog/:categories/:title
defaults:
    -
        scope:
            path: ""
        values:
            layout: default
            links:
                - title: Home
                  ref: /
                  color: '#e53935'
                - title: Resume
                  ref: /resume/
                  color: '#bf5700'
                - title: Schedule
                  ref: /schedule/
                  color: '#03a9f4'
                - title: Projects
                  ref: /projects/
                  color: '#4caf50'
                - title: Blog
                  ref: /blog/
                  color: '#ffeb3b'
    -
        scope:
            path: "cs373"
        values:
            layout: sweblog
            part1: 'What did you do this past week?'
            part2: "What's in your way?"
            part3: 'What will you do next week?'
            part4: 'Class experience'
            part5: 'Tip of the week'

sass:
    style: compressed
    sass-dir: _sass

