permalink: /blog/:categories/:title
defaults:
    -
        scope:
            path: ""
        values:
            layout: default
            links:
                Home: /
                Schedule: /schedule/
                Projects: /projects/
                Hobbies: /hobbies/
                Blog: /blog/

