#!/bin/bash
printf "var taxiData = [\n"
while IFS= read -r addr; do
        json=$(curl -s "https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyD4mfJfckcRUhQoZt7_PFSaJBAPHNauorg&address=$addr")
        printf "  new google.maps.LatLng("
        echo $json \
            | jq ".results[0].geometry.location.lat" \
            | perl -pe 's/\n/, /'
        echo $json \
            | jq ".results[0].geometry.location.lng" \
            | perl -pe 's/\n/),\n/'
done
printf "];"
